package com.bytewave.apiversionspringbootstarter;

import com.bytewave.apiversionspringbootstarter.version.EnableApiVersioning;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableApiVersioning
public class ApiVersionSpringBootStarterApplication {

    public static void main(String[] args) {
        SpringApplication.run(ApiVersionSpringBootStarterApplication.class, args);
    }

}
